### ISSUE TITLE
Compiler issue with Xcode 15.3 & C++20

### ISSUE THREAD

**Issue by asnagni** [macmade/Objective-CPP#3]
Hi,
   I'm trying to use your library in our project using a c++20 compiler (the IDE is Xcode) and we are having a compilation error（Please see attachments).
   
   Could you please let me know how we can fix it effectively without braking your code.
   
  ![Untitled](https://github.com/macmade/Objective-CPP/assets/37470668/031059a0-5e7e-4cfd-a00f-2047f15c2edf)
  
  ![image](https://github.com/macmade/Objective-CPP/assets/37470668/e58e82dc-c870-40d5-8139-0c1b34d79857)

   Thank you,
   Stay safe

**Comment by macmade** [comment]
I just tried to compile and test the library with C++20 without issues.

Based on the compiler error, it looks like you're not using it properly.  
Can you show the code which calls `DictionaryFromMap`?

(it would be great if you could avoid posting code screenshots, by the way)

**Comment by asnagni** [comment]
I can send you the file.

**Comment by macmade** [comment]
Just post the code calling into `DictionaryFromMap` here...

**Comment by asnagni** [comment]
Please see attachment. It’s a big file, lot of things are going on.


￼

For “MapFromDictionary” Check on line:
 1)   5354
 2)    5582
 3)   9467
 4)    9963
 5)   10009


We are so using the string a vector converters.
By the way it’s a great library. It was working fine  using C++ 11 & 14 but we are having a problem when we moved to C++20

Thank you,
Stay safe

**Comment by asnagni** [comment]
Ok let me do that.

**Comment by asnagni** [comment]
Example 1:                                 

   id mediaObject = [pMediaDictionary objectForKeyedSubscript:mediaMapKey];
   std::map <std::string, std::string> mediaItem;
   mediaItem = ObjectiveCPP::MapFromDictionary< std::string, NSString >(mediaObject, @selector( cppString ) );

Example 2:   
   id bonuxObject = [pBonusDictionary objectForKeyedSubscript:bonusMapKey];
   std::map <std::string, std::string> bonusItem;
   bonusItem = ObjectiveCPP::MapFromDictionary< std::string, NSString >(bonuxObject, @selector( cppString ) );


Example 3:  
m_groupsMap = ObjectiveCPP::MapFromDictionary< std::string, NSString >(documentDiff.document.data[@"groups"],
                                                                                                   @selector( cppString ) );


Thank you,
Stay safe

**Comment by macmade** [comment]
I don't think these are the lines causing your issue.  
I can compile this code with Xcode 15.3 and C++ 20 without errors.

There's also a unit test for that case:  
https://github.com/macmade/Objective-CPP/blob/05e277553cdf0e34669ab8204d177d27d918950d/Unit-Tests/Test-Map.mm#L181

Based on the compiler error you showed, you're calling `MapFromDictionary` with **3 arguments**.  
Please show the relevant code.

**Comment by asnagni** [comment]
Hi,
	Thank for the link, I do appreciate. I did triple check again and in the code that I sent you there is no call with 3 parameters.

	The only place that there is 3 parameters are passed to MapFromDictionary with 3 arguments. It is in Objective-CPP. I did a global search to show you. Please check the screenshot below.


￼

This is the code from Objective-CPP passing 3 parameters:

    template < typename T, typename ObjCClass >
    std::map< T, T > MapFromDictionary( NSDictionary * dictionary, SEL getter )
    {
        return MapFromDictionary< T, T, ObjCClass, ObjCClass >( dictionary, getter, getter );
    }

Thank you.

**Comment by macmade** [comment]
Can you show me the complete compiler error from Xcode's build log?

<img width="356" alt="Xcode" src="https://github.com/macmade/Objective-CPP/assets/146476/e3c453a8-b5e3-412d-b19d-4ebac1a39fa7">

**Comment by asnagni** [comment]
Sure, please see below:

Candidate function template not viable: no known conversion from 'NSString *(^)(const std::string &)' to 'SEL _Nonnull' for 2nd argument
Candidate function template not viable: requires 2 arguments, but 3 were provided

**Comment by asnagni** [comment]
I just checked the code in Objective-CPP where we are passing 3 arguments. It's in Map.mm
This is what I see:

#import <ObjectiveCPP.hpp>

namespace ObjectiveCPP
{
    NSDictionary * DictionaryFromMap( const std::map< std::string, std::string > & map )
    {
        return DictionaryFromMap< std::string, std::string, NSString, NSString >
        (
            map,
            ^( const std::string & s )
            {
                return [ [ NSString alloc ] initWithCPPString: s ];
            },
            ^( const std::string & s )
            {
                return [ [ NSString alloc ] initWithCPPString: s ];
            }
        );
    }
}

**Comment by asnagni** [comment]
I just took a screenshot. That mau=y help identify the issue:

￼

**Comment by asnagni** [comment]
In case you can read the compiler message on the screenshot, this is the message:

No matching function for call to ‘DictionaryFromMap'

Thank you.

**Comment by macmade** [comment]
I need the complete compiler error.  
You can expand the message to get more details:

<img width="84" alt="Error" src="https://github.com/macmade/Objective-CPP/assets/146476/f4b596a0-4db5-4632-a37b-dfced72de777">

**Comment by asnagni** [comment]
That all it is giving me. But Xcode is not very smart for helping. Let me make a build clean and build again. Perhaps it will give me more information.

**Comment by macmade** [comment]
Go to the build log, click on the failed build action, expand the message, as shown in the screenshot.  
It will give the information I need.

**Comment by asnagni** [comment]
Ok this is entire output:

/////
iphoneos/Objects-normal/arm64/Map.o /Users/asnagni/project/system/AxmolPojects/BeBetter/libs/ObjectiveCPP/source/Map.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'BeBetter' from project 'BeBetter')
    cd /Users/asnagni/project/system/AxmolPojects/BeBetter
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -ivfsstatcache /Users/asnagni/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos17.4-21E210-99a79c02cfa501706f5b564e46d84afe.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -index-store-path /Users/asnagni/Library/Developer/Xcode/DerivedData/BeBetter-cgednnbzvqjspmazshcdqxoodebr/Index.noindex/DataStore @/Users/asnagni/project/system/AxmolPojects/BeBetter/build_ios_arm64/build/BeBetter.build/Debug-iphoneos/Objects-normal/arm64/af3fcb34312c57c0f52879cdce924b91-common-args.resp -MMD -MT dependencies -MF /Users/asnagni/project/system/AxmolPojects/BeBetter/build_ios_arm64/build/BeBetter.build/Debug-iphoneos/Objects-normal/arm64/Map.d --serialize-diagnostics /Users/asnagni/project/system/AxmolPojects/BeBetter/build_ios_arm64/build/BeBetter.build/Debug-iphoneos/Objects-normal/arm64/Map.dia -c /Users/asnagni/project/system/AxmolPojects/BeBetter/libs/ObjectiveCPP/source/Map.mm -o /Users/asnagni/project/system/AxmolPojects/BeBetter/build_ios_arm64/build/BeBetter.build/Debug-iphoneos/Objects-normal/arm64/Map.o

/Users/asnagni/project/system/AxmolPojects/BeBetter/libs/ObjectiveCPP/source/Map.mm:36:16: error: no matching function for call to 'DictionaryFromMap'
        return DictionaryFromMap< std::string, std::string, NSString, NSString >
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/asnagni/project/system/AxmolPojects/BeBetter/libs/ObjectiveCPP/source/Map.mm:30:
In file included from /Users/asnagni/project/system/AxmolPojects/BeBetter/libs/ObjectiveCPP/include/ObjectiveCPP.hpp:45:
/Users/asnagni/project/system/AxmolPojects/BeBetter/libs/ObjectiveCPP/include/ObjectiveCPP/Map.hpp:49:20: note: candidate function template not viable: no known conversion from 'NSString *(^)(const std::string &)' to 'SEL _Nonnull' for 2nd argument
    NSDictionary * DictionaryFromMap( const std::map< TK, TV > & map, SEL initMethodK, SEL initMethodV )
                   ^
/Users/asnagni/project/system/AxmolPojects/BeBetter/libs/ObjectiveCPP/include/ObjectiveCPP/Map.hpp:93:20: note: candidate function template not viable: requires 2 arguments, but 3 were provided
    NSDictionary * DictionaryFromMap( const std::map< T, T > & map, SEL initMethod )
                   ^
1 error generated.

**Comment by macmade** [comment]
I just tested with iOS, no problem with C++20.  
Which version of Objective-CPP are you using?

**Comment by asnagni** [comment]
We downloaded the latest one. On the website.

**Comment by asnagni** [comment]
Hi,
   I looked at carefully the Objective-CPP code and I was able to make 2 changes and I’m able to have to compile now:
1) I renamed the function “MapFromDictionary” with 3 parameters from “MapFromDictionary" to “MapFromDictionaryInternal” . I need to make the change a two place. Where it was defined and where it was called.

2) I was having a second issue in the Map.mm file reported by the compiler that I shared with you: Therefore I reverted back the Objective-CPP code to the previous code that you used to have. So I went from a) to b):

	a:
       namespace ObjectiveCPP
{
    NSDictionary * DictionaryFromMap( const std::map< std::string, std::string > & map )
    {
        return DictionaryFromMap< std::string, std::string, NSString, NSString >
        (
            map,
            ^( const std::string & s )
            {
                return [ [ NSString alloc ] initWithCPPString: s ];
            },
            ^( const std::string & s )
            {
                return [ [ NSString alloc ] initWithCPPString: s ];
            }
        );
    }
}


	b:
namespace ObjectiveCPP
{
    NSDictionary * DictionaryFromMap( const std::map< std::string, std::string > & map )
    {
        return DictionaryFromMap< std::string, std::string, NSString, NSString >( map, @selector( initWithCPPString: ), @selector( initWithCPPString: ) );
    }
}
              

Please let me know if you want me to send you the 2 files that I modified.

**Comment by macmade** [comment]
Please format code when you post…

**Comment by macmade** [comment]
Your compiler output is odd.  
I guess you're not using the provided library but instead compiling the sources directly into your project.

There's no reason for your changes. The whole library builds fine with C++20 as is.

It means your Xcode project is not set-up properly.

**Comment by asnagni** [comment]
Hi,
	Yes you are right, I’m building from the source. I will try by the end of the day to use the provided library and see how it works. I will be using the lastest library you provided.  I will keep you posted. 

Thank you.

**Comment by asnagni** [comment]
By the way, which version should I use? Just to make sure I’m getting the correct version.

Thank you

**Comment by macmade** [comment]
Latest commit from main, that is 05e277553cdf0e34669ab8204d177d27d918950d

**Comment by asnagni** [comment]
Thank you.

**Comment by macmade** [comment]
Closing...
Feel free to reopen if you still have issues.
